### ISSUE TITLE
CreateInstance fail, File not Found, VS 2019

### ISSUE THREAD

**Issue by rober423** [niklaskallander/vs-unobtrusive-code#13]
CreateInstance failed for package [UnobtrusiveCodePackage]Source: "mscorlib" Description: Could not load file or assembly "Microsoft.VisualStudio.Shell.15.0, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" or one of its dependencies. The system cannot find the file specified.
System.IO.FileNotFoundException: Could not load file or assembly "Microsoft.VisualStudio.Shell.15.0, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" or one of its dependencies. The system cannot find the file specified.
File name: "Microsoft.VisualStudio.Shell.15.0, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"
   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by niklaskallander** [comment]
Hi, thanks for the report!

I’ll see if I can manage time to look into this over the weekend.

**Comment by niklaskallander** [comment]
I won't make this extension support VS 2019 going forward. I can't even figure out how to get Visual Studio 2019 anymore (besides buying a license, I'm a Community edition user, can't find a download for it 👎).
